fastlane_version "2.84.0"
default_platform :ios

platform :ios do

  # Common

  lane :run_unit_tests do
    scan(
      scheme: 'TestingWithCoreData-Example',
      skip_build: true
    )
  end

end
